{
    "result": true,
    "data": [
        {
            "id": "1",
            "currency": "USD",
            "schedules": [
                {
                    "date": "2026-09-02T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-02T00:00:00",
                            "stdutc": "2026-09-02T00:00:00",
                            "sta": "2026-09-02T00:00:00",
                            "stautc": "2026-09-02T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D30327E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-02T00:00:00",
                                    "stdutc": "2026-09-02T00:00:00",
                                    "sta": "2026-09-02T00:00:00",
                                    "stautc": "2026-09-02T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-02T00:00:00",
                                            "stdutc": "2026-09-02T00:00:00",
                                            "sta": "2026-09-02T00:00:00",
                                            "stautc": "2026-09-02T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 157.68,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 157.68,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443330333237453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-03T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-03T00:00:00",
                            "stdutc": "2026-09-03T00:00:00",
                            "sta": "2026-09-03T00:00:00",
                            "stautc": "2026-09-03T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D30337E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-03T00:00:00",
                                    "stdutc": "2026-09-03T00:00:00",
                                    "sta": "2026-09-03T00:00:00",
                                    "stautc": "2026-09-03T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-03T00:00:00",
                                            "stdutc": "2026-09-03T00:00:00",
                                            "sta": "2026-09-03T00:00:00",
                                            "stautc": "2026-09-03T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 157.68,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 157.68,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443330333337453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-04T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-04T00:00:00",
                            "stdutc": "2026-09-04T00:00:00",
                            "sta": "2026-09-04T00:00:00",
                            "stautc": "2026-09-04T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D30347E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-04T00:00:00",
                                    "stdutc": "2026-09-04T00:00:00",
                                    "sta": "2026-09-04T00:00:00",
                                    "stautc": "2026-09-04T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-04T00:00:00",
                                            "stdutc": "2026-09-04T00:00:00",
                                            "sta": "2026-09-04T00:00:00",
                                            "stautc": "2026-09-04T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 215.66,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 215.66,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443330333437453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-05T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-05T00:00:00",
                            "stdutc": "2026-09-05T00:00:00",
                            "sta": "2026-09-05T00:00:00",
                            "stautc": "2026-09-05T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D30357E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-05T00:00:00",
                                    "stdutc": "2026-09-05T00:00:00",
                                    "sta": "2026-09-05T00:00:00",
                                    "stautc": "2026-09-05T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-05T00:00:00",
                                            "stdutc": "2026-09-05T00:00:00",
                                            "sta": "2026-09-05T00:00:00",
                                            "stautc": "2026-09-05T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 192.47,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 192.47,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443330333537453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-06T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-06T00:00:00",
                            "stdutc": "2026-09-06T00:00:00",
                            "sta": "2026-09-06T00:00:00",
                            "stautc": "2026-09-06T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D30367E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-06T00:00:00",
                                    "stdutc": "2026-09-06T00:00:00",
                                    "sta": "2026-09-06T00:00:00",
                                    "stautc": "2026-09-06T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-06T00:00:00",
                                            "stdutc": "2026-09-06T00:00:00",
                                            "sta": "2026-09-06T00:00:00",
                                            "stautc": "2026-09-06T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 204.06,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 204.06,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443330333637453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-07T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-07T00:00:00",
                            "stdutc": "2026-09-07T00:00:00",
                            "sta": "2026-09-07T00:00:00",
                            "stautc": "2026-09-07T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D30377E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-07T00:00:00",
                                    "stdutc": "2026-09-07T00:00:00",
                                    "sta": "2026-09-07T00:00:00",
                                    "stautc": "2026-09-07T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-07T00:00:00",
                                            "stdutc": "2026-09-07T00:00:00",
                                            "sta": "2026-09-07T00:00:00",
                                            "stautc": "2026-09-07T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 192.47,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 192.47,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443330333737453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-08T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-08T00:00:00",
                            "stdutc": "2026-09-08T00:00:00",
                            "sta": "2026-09-08T00:00:00",
                            "stautc": "2026-09-08T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D30387E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-08T00:00:00",
                                    "stdutc": "2026-09-08T00:00:00",
                                    "sta": "2026-09-08T00:00:00",
                                    "stautc": "2026-09-08T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-08T00:00:00",
                                            "stdutc": "2026-09-08T00:00:00",
                                            "sta": "2026-09-08T00:00:00",
                                            "stautc": "2026-09-08T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 150.72,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 150.72,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443330333837453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-09T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-09T00:00:00",
                            "stdutc": "2026-09-09T00:00:00",
                            "sta": "2026-09-09T00:00:00",
                            "stautc": "2026-09-09T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D30397E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-09T00:00:00",
                                    "stdutc": "2026-09-09T00:00:00",
                                    "sta": "2026-09-09T00:00:00",
                                    "stautc": "2026-09-09T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-09T00:00:00",
                                            "stdutc": "2026-09-09T00:00:00",
                                            "sta": "2026-09-09T00:00:00",
                                            "stautc": "2026-09-09T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 180.87,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 180.87,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443330333937453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-10T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-10T00:00:00",
                            "stdutc": "2026-09-10T00:00:00",
                            "sta": "2026-09-10T00:00:00",
                            "stautc": "2026-09-10T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D31307E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-10T00:00:00",
                                    "stdutc": "2026-09-10T00:00:00",
                                    "sta": "2026-09-10T00:00:00",
                                    "stautc": "2026-09-10T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-10T00:00:00",
                                            "stdutc": "2026-09-10T00:00:00",
                                            "sta": "2026-09-10T00:00:00",
                                            "stautc": "2026-09-10T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 150.72,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 150.72,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443331333037453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-11T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-11T00:00:00",
                            "stdutc": "2026-09-11T00:00:00",
                            "sta": "2026-09-11T00:00:00",
                            "stautc": "2026-09-11T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D31317E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-11T00:00:00",
                                    "stdutc": "2026-09-11T00:00:00",
                                    "sta": "2026-09-11T00:00:00",
                                    "stautc": "2026-09-11T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-11T00:00:00",
                                            "stdutc": "2026-09-11T00:00:00",
                                            "sta": "2026-09-11T00:00:00",
                                            "stautc": "2026-09-11T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 204.06,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 204.06,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443331333137453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-12T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-12T00:00:00",
                            "stdutc": "2026-09-12T00:00:00",
                            "sta": "2026-09-12T00:00:00",
                            "stautc": "2026-09-12T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D31327E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-12T00:00:00",
                                    "stdutc": "2026-09-12T00:00:00",
                                    "sta": "2026-09-12T00:00:00",
                                    "stautc": "2026-09-12T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-12T00:00:00",
                                            "stdutc": "2026-09-12T00:00:00",
                                            "sta": "2026-09-12T00:00:00",
                                            "stautc": "2026-09-12T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 179.71,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 179.71,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443331333237453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-13T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-13T00:00:00",
                            "stdutc": "2026-09-13T00:00:00",
                            "sta": "2026-09-13T00:00:00",
                            "stautc": "2026-09-13T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D31337E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-13T00:00:00",
                                    "stdutc": "2026-09-13T00:00:00",
                                    "sta": "2026-09-13T00:00:00",
                                    "stautc": "2026-09-13T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-13T00:00:00",
                                            "stdutc": "2026-09-13T00:00:00",
                                            "sta": "2026-09-13T00:00:00",
                                            "stautc": "2026-09-13T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 204.06,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 204.06,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443331333337453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-14T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-14T00:00:00",
                            "stdutc": "2026-09-14T00:00:00",
                            "sta": "2026-09-14T00:00:00",
                            "stautc": "2026-09-14T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D31347E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-14T00:00:00",
                                    "stdutc": "2026-09-14T00:00:00",
                                    "sta": "2026-09-14T00:00:00",
                                    "stautc": "2026-09-14T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-14T00:00:00",
                                            "stdutc": "2026-09-14T00:00:00",
                                            "sta": "2026-09-14T00:00:00",
                                            "stautc": "2026-09-14T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 198.26,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 198.26,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443331333437453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-15T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-15T00:00:00",
                            "stdutc": "2026-09-15T00:00:00",
                            "sta": "2026-09-15T00:00:00",
                            "stautc": "2026-09-15T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D31357E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-15T00:00:00",
                                    "stdutc": "2026-09-15T00:00:00",
                                    "sta": "2026-09-15T00:00:00",
                                    "stautc": "2026-09-15T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-15T00:00:00",
                                            "stdutc": "2026-09-15T00:00:00",
                                            "sta": "2026-09-15T00:00:00",
                                            "stautc": "2026-09-15T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 127.53,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 127.53,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443331333537453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-16T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-16T00:00:00",
                            "stdutc": "2026-09-16T00:00:00",
                            "sta": "2026-09-16T00:00:00",
                            "stautc": "2026-09-16T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D31367E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-16T00:00:00",
                                    "stdutc": "2026-09-16T00:00:00",
                                    "sta": "2026-09-16T00:00:00",
                                    "stautc": "2026-09-16T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-16T00:00:00",
                                            "stdutc": "2026-09-16T00:00:00",
                                            "sta": "2026-09-16T00:00:00",
                                            "stautc": "2026-09-16T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 163.48,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 163.48,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443331333637453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-17T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-17T00:00:00",
                            "stdutc": "2026-09-17T00:00:00",
                            "sta": "2026-09-17T00:00:00",
                            "stautc": "2026-09-17T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D31377E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-17T00:00:00",
                                    "stdutc": "2026-09-17T00:00:00",
                                    "sta": "2026-09-17T00:00:00",
                                    "stautc": "2026-09-17T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-17T00:00:00",
                                            "stdutc": "2026-09-17T00:00:00",
                                            "sta": "2026-09-17T00:00:00",
                                            "stautc": "2026-09-17T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 139.13,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 139.13,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443331333737453334343633343334333333317E"
                        },
                        {
                            "duration": "03:50:00",
                            "origin": "DUS",
                            "destination": "COV",
                            "originCountry": "DE",
                            "destinationCountry": "TR",
                            "std": "2026-09-17T20:40:00",
                            "stdutc": "2026-09-17T18:40:00",
                            "sta": "2026-09-18T01:30:00",
                            "stautc": "2026-09-17T22:30:00",
                            "referenceId": "FL1",
                            "scheduleType": "AllPrice",
                            "segments": [
                                {
                                    "duration": "03:50:00",
                                    "id": "4455537E434F567E313337317E58517E323032362D30392D31377E353334353437333137433533343534373336374335333435343733313331",
                                    "referenceId": "SEG1|SEG6|SEG11",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "originCountry": "DE",
                                    "destinationCountry": "TR",
                                    "std": "2026-09-17T20:40:00",
                                    "stdutc": "2026-09-17T18:40:00",
                                    "sta": "2026-09-18T01:30:00",
                                    "stautc": "2026-09-17T22:30:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "originCountry": "DE",
                                            "destinationCountry": "TR",
                                            "std": "2026-09-17T20:40:00",
                                            "stdutc": "2026-09-17T18:40:00",
                                            "sta": "2026-09-18T01:30:00",
                                            "stautc": "2026-09-17T22:30:00",
                                            "duration": "03:50:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": "XQ",
                                            "operatingAirlineCode": "XQ~"
                                        },
                                        "type": "Plane",
                                        "name": "E",
                                        "model": "73H",
                                        "number": "1371"
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "53554E56414C55457E7E50433253554E56414C55457E5043327E4144547E7E344634363334333236353636333436323330333332443631333636313331324433313331363633313244363133393635333332443336363236353336333136363337363436313338333333323745344634363439333433323635363633343632333033333244363133363631333132443331333136363331324436313339363533333244333636323635333633313636333736343631333833333332333137453533343534373336",
                                    "referenceId": "OF42ef4b03-a6a1-11f1-a9e3-6be61f7da832~OFI42ef4b03-a6a1-11f1-a9e3-6be61f7da8321~SEG6",
                                    "fareBasisCode": "PC2SUNVALUE",
                                    "classOfService": "PC2",
                                    "productClass": "SUNVALUE",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 139.13,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "SUNVALUE",
                                            "amount": 139.13,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false,
                                    "items": [
                                        {
                                            "code": "ABAG",
                                            "name": "1 large piece of hand baggage (max. 8 kg & 55x40x23 cm)",
                                            "description": "Title|Hand Baggage ~ Description1|8 kg, 55x40x23 cm",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "20KG",
                                            "name": "Checked baggage (max. 20 kg)",
                                            "description": "Title|Checked Baggage ~ Description1|Max. ~ Description2|20 kg",
                                            "applicability": "Included"
                                        }
                                    ]
                                },
                                {
                                    "id": "53554E45434F504C55537E7E50433153554E45434F504C55537E5043317E4144547E7E344634363334333236353636333436313636363132443631333636313331324433313331363633313244363133393635333332443635363233383337333533363338363236353338333233343745344634363439333433323635363633343631363636313244363133363631333132443331333136363331324436313339363533333244363536323338333733353336333836323635333833323334333137453533343534373331",
                                    "referenceId": "OF42ef4afa-a6a1-11f1-a9e3-eb87568be824~OFI42ef4afa-a6a1-11f1-a9e3-eb87568be8241~SEG1",
                                    "fareBasisCode": "PC1SUNECOPLUS",
                                    "classOfService": "PC1",
                                    "productClass": "SUNECOPLUS",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 150.73,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "SUNECOPLUS",
                                            "amount": 150.73,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false,
                                    "items": [
                                        {
                                            "code": "ABAG",
                                            "name": "1 large piece of hand baggage (max. 8 kg & 55x40x23 cm)",
                                            "description": "Title|Hand Baggage ~ Description1|8 kg, 55x40x23 cm",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "30KG",
                                            "name": "Checked baggage (max. 30 kg)",
                                            "description": "Title|Checked Baggage ~ Description1|Max. ~ Description2|30 kg",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "FLXX7",
                                            "name": "Sunflex 7 Rebook up to 7 days before departure free of charge (+ price difference)",
                                            "description": "Title|Rebooking ~ Description1|Before departure (fare difference applies) ~ Description2|Up to 7 Days",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "OCFE",
                                            "name": "Free Online Check-in & Airport Check-in",
                                            "description": "Title|Airport Check-in ~ Description1|(Free online check-in on all fares)",
                                            "applicability": "Included"
                                        }
                                    ]
                                },
                                {
                                    "id": "53554E434F4D464F52547E7E50433353554E434F4D464F52547E5043337E4144547E7E3446343633343332363536363337333233313633324436313336363133313244333133313636333132443631333936353333324433393632333436343333333133333631363436323332333237453446343634393334333236353636333733323331363332443631333636313331324433313331363633313244363133393635333332443339363233343634333333313333363136343632333233323331374535333435343733313331",
                                    "referenceId": "OF42ef721c-a6a1-11f1-a9e3-9b4d313adb22~OFI42ef721c-a6a1-11f1-a9e3-9b4d313adb221~SEG11",
                                    "fareBasisCode": "PC3SUNCOMFORT",
                                    "classOfService": "PC3",
                                    "productClass": "SUNCOMFORT",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 173.92,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "SUNCOMFORT",
                                            "amount": 173.92,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false,
                                    "items": [
                                        {
                                            "code": "ABAG",
                                            "name": "1 large piece of hand baggage (max. 8 kg & 55x40x23 cm)",
                                            "description": "Title|Hand Baggage ~ Description1|8 kg, 55x40x23 cm",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "35KG",
                                            "name": "Checked baggage (max. 35 kg)",
                                            "description": "Title|Checked Baggage ~ Description1|Max. ~ Description2|35 kg",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "FLXX3",
                                            "name": "Sunflex 3 Rebook up to 3 days before departure free of charge (+ price difference)",
                                            "description": "Title|Rebooking ~ Description1|Before departure (fare difference applies) ~ Description2|Up to 3 Days",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "OCFE",
                                            "name": "Free Online Check-in & Airport Check-in",
                                            "description": "Title|Airport Check-in ~ Description1|(Free online check-in on all fares)",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "STRD",
                                            "name": "Standard Seat Reservation",
                                            "description": "Title|Seat Reservation",
                                            "applicability": "Included"
                                        }
                                    ]
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374533313333333733313745353835313745333233303332333632443330333932443331333737453335333333343335333433373333333133373433333533333334333533343337333333363337343333353333333433353334333733333331333333317E343634433331"
                        },
                        {
                            "duration": "06:00:00",
                            "origin": "DUS",
                            "destination": "COV",
                            "originCountry": "DE",
                            "destinationCountry": "TR",
                            "std": "2026-09-17T15:05:00",
                            "stdutc": "2026-09-17T13:05:00",
                            "sta": "2026-09-17T22:05:00",
                            "stautc": "2026-09-17T19:05:00",
                            "referenceId": "FL3",
                            "scheduleType": "AllPrice",
                            "segments": [
                                {
                                    "duration": "03:15:00",
                                    "id": "4455537E4144427E3935397E58517E323032362D30392D31377E353334353437333437433533343534373339374335333435343733313334",
                                    "referenceId": "SEG4|SEG9|SEG14",
                                    "origin": "DUS",
                                    "destination": "ADB",
                                    "originCountry": "DE",
                                    "destinationCountry": "TR",
                                    "std": "2026-09-17T15:05:00",
                                    "stdutc": "2026-09-17T13:05:00",
                                    "sta": "2026-09-17T19:20:00",
                                    "stautc": "2026-09-17T16:20:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "ADB",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "originCountry": "DE",
                                            "destinationCountry": "TR",
                                            "std": "2026-09-17T15:05:00",
                                            "stdutc": "2026-09-17T13:05:00",
                                            "sta": "2026-09-17T19:20:00",
                                            "stautc": "2026-09-17T16:20:00",
                                            "duration": "03:15:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": "XQ",
                                            "operatingAirlineCode": "XQ~"
                                        },
                                        "type": "Plane",
                                        "name": "D",
                                        "model": "7M8",
                                        "number": "959"
                                    }
                                },
                                {
                                    "duration": "01:25:00",
                                    "id": "4144427E434F567E393330367E58517E323032362D30392D31377E3533343534373335374335333435343733313330374335333435343733313335",
                                    "referenceId": "SEG5|SEG10|SEG15",
                                    "origin": "ADB",
                                    "destination": "COV",
                                    "originCountry": "TR",
                                    "destinationCountry": "TR",
                                    "std": "2026-09-17T20:40:00",
                                    "stdutc": "2026-09-17T17:40:00",
                                    "sta": "2026-09-17T22:05:00",
                                    "stautc": "2026-09-17T19:05:00",
                                    "legs": [
                                        {
                                            "origin": "ADB",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "originCountry": "TR",
                                            "destinationCountry": "TR",
                                            "std": "2026-09-17T20:40:00",
                                            "stdutc": "2026-09-17T17:40:00",
                                            "sta": "2026-09-17T22:05:00",
                                            "stautc": "2026-09-17T19:05:00",
                                            "duration": "01:25:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": "XQ",
                                            "operatingAirlineCode": "XQ~"
                                        },
                                        "type": "Plane",
                                        "name": "A1",
                                        "model": "7M8",
                                        "number": "9306"
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "53554E56414C55457E7E50433253554E56414C55457E5043327E4144547E7E344634363334333236353636333436323330333932443631333636313331324433313331363633313244363133393635333332443633333333323632333433373334363533393339363236343745344634363439333433323635363633343632333033393244363133363631333132443331333136363331324436313339363533333244363333333332363233343337333436353339333936323634333137453533343534373339374335333435343733313330",
                                    "referenceId": "OF42ef4b09-a6a1-11f1-a9e3-c32b474e99bd~OFI42ef4b09-a6a1-11f1-a9e3-c32b474e99bd1~SEG9|SEG10",
                                    "fareBasisCode": "PC2SUNVALUE",
                                    "classOfService": "PC2",
                                    "productClass": "SUNVALUE",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 163.48,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "SUNVALUE",
                                            "amount": 163.48,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false,
                                    "items": [
                                        {
                                            "code": "ABAG",
                                            "name": "1 large piece of hand baggage (max. 8 kg & 55x40x23 cm)",
                                            "description": "Title|Hand Baggage ~ Description1|8 kg, 55x40x23 cm",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "20KG",
                                            "name": "Checked baggage (max. 20 kg)",
                                            "description": "Title|Checked Baggage ~ Description1|Max. ~ Description2|20 kg",
                                            "applicability": "Included"
                                        }
                                    ]
                                },
                                {
                                    "id": "53554E45434F504C55537E7E50433153554E45434F504C55537E5043317E4144547E7E34463436333433323635363633343632333033303244363133363631333132443331333136363331324436313339363533333244363236323338363333323636363133333337333936363330374534463436343933343332363536363334363233303330324436313336363133313244333133313636333132443631333936353333324436323632333836333332363636313333333733393636333033313745353334353437333437433533343534373335",
                                    "referenceId": "OF42ef4b00-a6a1-11f1-a9e3-bb8c2fa379f0~OFI42ef4b00-a6a1-11f1-a9e3-bb8c2fa379f01~SEG4|SEG5",
                                    "fareBasisCode": "PC1SUNECOPLUS",
                                    "classOfService": "PC1",
                                    "productClass": "SUNECOPLUS",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 175.08,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "SUNECOPLUS",
                                            "amount": 175.08,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false,
                                    "items": [
                                        {
                                            "code": "ABAG",
                                            "name": "1 large piece of hand baggage (max. 8 kg & 55x40x23 cm)",
                                            "description": "Title|Hand Baggage ~ Description1|8 kg, 55x40x23 cm",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "30KG",
                                            "name": "Checked baggage (max. 30 kg)",
                                            "description": "Title|Checked Baggage ~ Description1|Max. ~ Description2|30 kg",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "FLXX7",
                                            "name": "Sunflex 7 Rebook up to 7 days before departure free of charge (+ price difference)",
                                            "description": "Title|Rebooking ~ Description1|Before departure (fare difference applies) ~ Description2|Up to 7 Days",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "OCFE",
                                            "name": "Free Online Check-in & Airport Check-in",
                                            "description": "Title|Airport Check-in ~ Description1|(Free online check-in on all fares)",
                                            "applicability": "Included"
                                        }
                                    ]
                                },
                                {
                                    "id": "53554E434F4D464F52547E7E50433353554E434F4D464F52547E5043337E4144547E7E3446343633343332363536363337333233323332324436313336363133313244333133313636333132443631333936353333324436343339363336363635363336363338333733393335333637453446343634393334333236353636333733323332333232443631333636313331324433313331363633313244363133393635333332443634333936333636363536333636333833373339333533363331374535333435343733313334374335333435343733313335",
                                    "referenceId": "OF42ef7222-a6a1-11f1-a9e3-d9cfecf87956~OFI42ef7222-a6a1-11f1-a9e3-d9cfecf879561~SEG14|SEG15",
                                    "fareBasisCode": "PC3SUNCOMFORT",
                                    "classOfService": "PC3",
                                    "productClass": "SUNCOMFORT",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 198.27,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "SUNCOMFORT",
                                            "amount": 198.27,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false,
                                    "items": [
                                        {
                                            "code": "ABAG",
                                            "name": "1 large piece of hand baggage (max. 8 kg & 55x40x23 cm)",
                                            "description": "Title|Hand Baggage ~ Description1|8 kg, 55x40x23 cm",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "35KG",
                                            "name": "Checked baggage (max. 35 kg)",
                                            "description": "Title|Checked Baggage ~ Description1|Max. ~ Description2|35 kg",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "FLXX3",
                                            "name": "Sunflex 3 Rebook up to 3 days before departure free of charge (+ price difference)",
                                            "description": "Title|Rebooking ~ Description1|Before departure (fare difference applies) ~ Description2|Up to 3 Days",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "OCFE",
                                            "name": "Free Online Check-in & Airport Check-in",
                                            "description": "Title|Airport Check-in ~ Description1|(Free online check-in on all fares)",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "STRD",
                                            "name": "Standard Seat Reservation",
                                            "description": "Title|Seat Reservation",
                                            "applicability": "Included"
                                        }
                                    ]
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "343435353533374534313434343237453339333533393745353835313745333233303332333632443330333932443331333737453335333333343335333433373333333433373433333533333334333533343337333333393337343333353333333433353334333733333331333333347E343134343432374534333446353637453339333333303336374535383531374533323330333233363244333033393244333133373745333533333334333533343337333333353337343333353333333433353334333733333331333333303337343333353333333433353334333733333331333333357E343634433333"
                        },
                        {
                            "duration": "12:30:00",
                            "origin": "DUS",
                            "destination": "COV",
                            "originCountry": "DE",
                            "destinationCountry": "TR",
                            "std": "2026-09-17T19:00:00",
                            "stdutc": "2026-09-17T17:00:00",
                            "sta": "2026-09-18T08:30:00",
                            "stautc": "2026-09-18T05:30:00",
                            "referenceId": "FL2",
                            "scheduleType": "AllPrice",
                            "segments": [
                                {
                                    "duration": "03:40:00",
                                    "id": "4455537E4159547E3138337E58517E323032362D30392D31377E353334353437333237433533343534373337374335333435343733313332",
                                    "referenceId": "SEG2|SEG7|SEG12",
                                    "origin": "DUS",
                                    "destination": "AYT",
                                    "originCountry": "DE",
                                    "destinationCountry": "TR",
                                    "std": "2026-09-17T19:00:00",
                                    "stdutc": "2026-09-17T17:00:00",
                                    "sta": "2026-09-17T23:40:00",
                                    "stautc": "2026-09-17T20:40:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "AYT",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "originCountry": "DE",
                                            "destinationCountry": "TR",
                                            "std": "2026-09-17T19:00:00",
                                            "stdutc": "2026-09-17T17:00:00",
                                            "sta": "2026-09-17T23:40:00",
                                            "stautc": "2026-09-17T20:40:00",
                                            "duration": "03:40:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": "XQ",
                                            "operatingAirlineCode": "XQ~"
                                        },
                                        "type": "Plane",
                                        "name": "A",
                                        "model": "73H",
                                        "number": "183"
                                    }
                                },
                                {
                                    "duration": "01:05:00",
                                    "id": "4159547E434F567E373633307E58517E323032362D30392D31387E353334353437333337433533343534373338374335333435343733313333",
                                    "referenceId": "SEG3|SEG8|SEG13",
                                    "origin": "AYT",
                                    "destination": "COV",
                                    "originCountry": "TR",
                                    "destinationCountry": "TR",
                                    "std": "2026-09-18T07:25:00",
                                    "stdutc": "2026-09-18T04:25:00",
                                    "sta": "2026-09-18T08:30:00",
                                    "stautc": "2026-09-18T05:30:00",
                                    "legs": [
                                        {
                                            "origin": "AYT",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "originCountry": "TR",
                                            "destinationCountry": "TR",
                                            "std": "2026-09-18T07:25:00",
                                            "stdutc": "2026-09-18T04:25:00",
                                            "sta": "2026-09-18T08:30:00",
                                            "stautc": "2026-09-18T05:30:00",
                                            "duration": "01:05:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": "XQ",
                                            "operatingAirlineCode": "XQ~"
                                        },
                                        "type": "Plane",
                                        "name": "A1",
                                        "model": "73H",
                                        "number": "7630"
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "53554E56414C55457E7E50433253554E56414C55457E5043327E4144547E7E34463436333433323635363633343632333033363244363133363631333132443331333136363331324436313339363533333244363636363632333433323338333936353334363136353631374534463436343933343332363536363334363233303336324436313336363133313244333133313636333132443631333936353333324436363636363233343332333833393635333436313635363133313745353334353437333737433533343534373338",
                                    "referenceId": "OF42ef4b06-a6a1-11f1-a9e3-ffb4289e4aea~OFI42ef4b06-a6a1-11f1-a9e3-ffb4289e4aea1~SEG7|SEG8",
                                    "fareBasisCode": "PC2SUNVALUE",
                                    "classOfService": "PC2",
                                    "productClass": "SUNVALUE",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 192.47,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "SUNVALUE",
                                            "amount": 192.47,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false,
                                    "items": [
                                        {
                                            "code": "ABAG",
                                            "name": "1 large piece of hand baggage (max. 8 kg & 55x40x23 cm)",
                                            "description": "Title|Hand Baggage ~ Description1|8 kg, 55x40x23 cm",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "20KG",
                                            "name": "Checked baggage (max. 20 kg)",
                                            "description": "Title|Checked Baggage ~ Description1|Max. ~ Description2|20 kg",
                                            "applicability": "Included"
                                        }
                                    ]
                                },
                                {
                                    "id": "53554E45434F504C55537E7E50433153554E45434F504C55537E5043317E4144547E7E34463436333433323635363633343631363636343244363133363631333132443331333136363331324436313339363533333244363233373332363236353337333233313635363233333335374534463436343933343332363536363334363136363634324436313336363133313244333133313636333132443631333936353333324436323337333236323635333733323331363536323333333533313745353334353437333237433533343534373333",
                                    "referenceId": "OF42ef4afd-a6a1-11f1-a9e3-b72be721eb35~OFI42ef4afd-a6a1-11f1-a9e3-b72be721eb351~SEG2|SEG3",
                                    "fareBasisCode": "PC1SUNECOPLUS",
                                    "classOfService": "PC1",
                                    "productClass": "SUNECOPLUS",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 204.07,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "SUNECOPLUS",
                                            "amount": 204.07,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false,
                                    "items": [
                                        {
                                            "code": "ABAG",
                                            "name": "1 large piece of hand baggage (max. 8 kg & 55x40x23 cm)",
                                            "description": "Title|Hand Baggage ~ Description1|8 kg, 55x40x23 cm",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "30KG",
                                            "name": "Checked baggage (max. 30 kg)",
                                            "description": "Title|Checked Baggage ~ Description1|Max. ~ Description2|30 kg",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "FLXX7",
                                            "name": "Sunflex 7 Rebook up to 7 days before departure free of charge (+ price difference)",
                                            "description": "Title|Rebooking ~ Description1|Before departure (fare difference applies) ~ Description2|Up to 7 Days",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "OCFE",
                                            "name": "Free Online Check-in & Airport Check-in",
                                            "description": "Title|Airport Check-in ~ Description1|(Free online check-in on all fares)",
                                            "applicability": "Included"
                                        }
                                    ]
                                },
                                {
                                    "id": "53554E434F4D464F52547E7E50433353554E434F4D464F52547E5043337E4144547E7E3446343633343332363536363337333233313636324436313336363133313244333133313636333132443631333936353333324433303337363436333338333333353330333736333336363137453446343634393334333236353636333733323331363632443631333636313331324433313331363633313244363133393635333332443330333736343633333833333335333033373633333636313331374535333435343733313332374335333435343733313333",
                                    "referenceId": "OF42ef721f-a6a1-11f1-a9e3-07dc83507c6a~OFI42ef721f-a6a1-11f1-a9e3-07dc83507c6a1~SEG12|SEG13",
                                    "fareBasisCode": "PC3SUNCOMFORT",
                                    "classOfService": "PC3",
                                    "productClass": "SUNCOMFORT",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 227.26,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "SUNCOMFORT",
                                            "amount": 227.26,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false,
                                    "items": [
                                        {
                                            "code": "ABAG",
                                            "name": "1 large piece of hand baggage (max. 8 kg & 55x40x23 cm)",
                                            "description": "Title|Hand Baggage ~ Description1|8 kg, 55x40x23 cm",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "35KG",
                                            "name": "Checked baggage (max. 35 kg)",
                                            "description": "Title|Checked Baggage ~ Description1|Max. ~ Description2|35 kg",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "FLXX3",
                                            "name": "Sunflex 3 Rebook up to 3 days before departure free of charge (+ price difference)",
                                            "description": "Title|Rebooking ~ Description1|Before departure (fare difference applies) ~ Description2|Up to 3 Days",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "OCFE",
                                            "name": "Free Online Check-in & Airport Check-in",
                                            "description": "Title|Airport Check-in ~ Description1|(Free online check-in on all fares)",
                                            "applicability": "Included"
                                        },
                                        {
                                            "code": "STRD",
                                            "name": "Standard Seat Reservation",
                                            "description": "Title|Seat Reservation",
                                            "applicability": "Included"
                                        }
                                    ]
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "343435353533374534313539353437453331333833333745353835313745333233303332333632443330333932443331333737453335333333343335333433373333333233373433333533333334333533343337333333373337343333353333333433353334333733333331333333327E3431353935343745343334463536374533373336333333303745353835313745333233303332333632443330333932443331333837453335333333343335333433373333333333373433333533333334333533343337333333383337343333353333333433353334333733333331333333337E343634433332"
                        }
                    ]
                },
                {
                    "date": "2026-09-18T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-18T00:00:00",
                            "stdutc": "2026-09-18T00:00:00",
                            "sta": "2026-09-18T00:00:00",
                            "stautc": "2026-09-18T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D31387E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-18T00:00:00",
                                    "stdutc": "2026-09-18T00:00:00",
                                    "sta": "2026-09-18T00:00:00",
                                    "stautc": "2026-09-18T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-18T00:00:00",
                                            "stdutc": "2026-09-18T00:00:00",
                                            "sta": "2026-09-18T00:00:00",
                                            "stautc": "2026-09-18T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 209.86,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 209.86,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443331333837453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-19T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-19T00:00:00",
                            "stdutc": "2026-09-19T00:00:00",
                            "sta": "2026-09-19T00:00:00",
                            "stautc": "2026-09-19T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D31397E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-19T00:00:00",
                                    "stdutc": "2026-09-19T00:00:00",
                                    "sta": "2026-09-19T00:00:00",
                                    "stautc": "2026-09-19T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-19T00:00:00",
                                            "stdutc": "2026-09-19T00:00:00",
                                            "sta": "2026-09-19T00:00:00",
                                            "stautc": "2026-09-19T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 162.32,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 162.32,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443331333937453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-20T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-20T00:00:00",
                            "stdutc": "2026-09-20T00:00:00",
                            "sta": "2026-09-20T00:00:00",
                            "stautc": "2026-09-20T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D32307E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-20T00:00:00",
                                    "stdutc": "2026-09-20T00:00:00",
                                    "sta": "2026-09-20T00:00:00",
                                    "stautc": "2026-09-20T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-20T00:00:00",
                                            "stdutc": "2026-09-20T00:00:00",
                                            "sta": "2026-09-20T00:00:00",
                                            "stautc": "2026-09-20T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 204.06,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 204.06,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443332333037453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-21T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-21T00:00:00",
                            "stdutc": "2026-09-21T00:00:00",
                            "sta": "2026-09-21T00:00:00",
                            "stautc": "2026-09-21T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D32317E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-21T00:00:00",
                                    "stdutc": "2026-09-21T00:00:00",
                                    "sta": "2026-09-21T00:00:00",
                                    "stautc": "2026-09-21T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-21T00:00:00",
                                            "stdutc": "2026-09-21T00:00:00",
                                            "sta": "2026-09-21T00:00:00",
                                            "stautc": "2026-09-21T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 163.48,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 163.48,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443332333137453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-22T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-22T00:00:00",
                            "stdutc": "2026-09-22T00:00:00",
                            "sta": "2026-09-22T00:00:00",
                            "stautc": "2026-09-22T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D32327E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-22T00:00:00",
                                    "stdutc": "2026-09-22T00:00:00",
                                    "sta": "2026-09-22T00:00:00",
                                    "stautc": "2026-09-22T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-22T00:00:00",
                                            "stdutc": "2026-09-22T00:00:00",
                                            "sta": "2026-09-22T00:00:00",
                                            "stautc": "2026-09-22T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 127.53,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 127.53,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443332333237453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-23T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-23T00:00:00",
                            "stdutc": "2026-09-23T00:00:00",
                            "sta": "2026-09-23T00:00:00",
                            "stautc": "2026-09-23T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D32337E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-23T00:00:00",
                                    "stdutc": "2026-09-23T00:00:00",
                                    "sta": "2026-09-23T00:00:00",
                                    "stautc": "2026-09-23T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-23T00:00:00",
                                            "stdutc": "2026-09-23T00:00:00",
                                            "sta": "2026-09-23T00:00:00",
                                            "stautc": "2026-09-23T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 151.88,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 151.88,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443332333337453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-24T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-24T00:00:00",
                            "stdutc": "2026-09-24T00:00:00",
                            "sta": "2026-09-24T00:00:00",
                            "stautc": "2026-09-24T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D32347E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-24T00:00:00",
                                    "stdutc": "2026-09-24T00:00:00",
                                    "sta": "2026-09-24T00:00:00",
                                    "stautc": "2026-09-24T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-24T00:00:00",
                                            "stdutc": "2026-09-24T00:00:00",
                                            "sta": "2026-09-24T00:00:00",
                                            "stautc": "2026-09-24T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 115.94,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 115.94,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443332333437453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-25T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-25T00:00:00",
                            "stdutc": "2026-09-25T00:00:00",
                            "sta": "2026-09-25T00:00:00",
                            "stautc": "2026-09-25T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D32357E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-25T00:00:00",
                                    "stdutc": "2026-09-25T00:00:00",
                                    "sta": "2026-09-25T00:00:00",
                                    "stautc": "2026-09-25T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-25T00:00:00",
                                            "stdutc": "2026-09-25T00:00:00",
                                            "sta": "2026-09-25T00:00:00",
                                            "stautc": "2026-09-25T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 163.48,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 163.48,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443332333537453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-26T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-26T00:00:00",
                            "stdutc": "2026-09-26T00:00:00",
                            "sta": "2026-09-26T00:00:00",
                            "stautc": "2026-09-26T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D32367E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-26T00:00:00",
                                    "stdutc": "2026-09-26T00:00:00",
                                    "sta": "2026-09-26T00:00:00",
                                    "stautc": "2026-09-26T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-26T00:00:00",
                                            "stdutc": "2026-09-26T00:00:00",
                                            "sta": "2026-09-26T00:00:00",
                                            "stautc": "2026-09-26T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 139.13,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 139.13,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443332333637453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-27T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-27T00:00:00",
                            "stdutc": "2026-09-27T00:00:00",
                            "sta": "2026-09-27T00:00:00",
                            "stautc": "2026-09-27T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D32377E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-27T00:00:00",
                                    "stdutc": "2026-09-27T00:00:00",
                                    "sta": "2026-09-27T00:00:00",
                                    "stautc": "2026-09-27T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-27T00:00:00",
                                            "stdutc": "2026-09-27T00:00:00",
                                            "sta": "2026-09-27T00:00:00",
                                            "stautc": "2026-09-27T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 163.48,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 163.48,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443332333737453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-28T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-28T00:00:00",
                            "stdutc": "2026-09-28T00:00:00",
                            "sta": "2026-09-28T00:00:00",
                            "stautc": "2026-09-28T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D32387E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-28T00:00:00",
                                    "stdutc": "2026-09-28T00:00:00",
                                    "sta": "2026-09-28T00:00:00",
                                    "stautc": "2026-09-28T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-28T00:00:00",
                                            "stdutc": "2026-09-28T00:00:00",
                                            "sta": "2026-09-28T00:00:00",
                                            "stautc": "2026-09-28T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 151.88,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 151.88,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443332333837453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-29T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-29T00:00:00",
                            "stdutc": "2026-09-29T00:00:00",
                            "sta": "2026-09-29T00:00:00",
                            "stautc": "2026-09-29T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D32397E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-29T00:00:00",
                                    "stdutc": "2026-09-29T00:00:00",
                                    "sta": "2026-09-29T00:00:00",
                                    "stautc": "2026-09-29T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-29T00:00:00",
                                            "stdutc": "2026-09-29T00:00:00",
                                            "sta": "2026-09-29T00:00:00",
                                            "stautc": "2026-09-29T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 127.53,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 127.53,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443332333937453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-09-30T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-09-30T00:00:00",
                            "stdutc": "2026-09-30T00:00:00",
                            "sta": "2026-09-30T00:00:00",
                            "stautc": "2026-09-30T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D30392D33307E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-09-30T00:00:00",
                                    "stdutc": "2026-09-30T00:00:00",
                                    "sta": "2026-09-30T00:00:00",
                                    "stautc": "2026-09-30T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-09-30T00:00:00",
                                            "stdutc": "2026-09-30T00:00:00",
                                            "sta": "2026-09-30T00:00:00",
                                            "stautc": "2026-09-30T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 151.88,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 151.88,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443330333932443333333037453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-10-01T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-10-01T00:00:00",
                            "stdutc": "2026-10-01T00:00:00",
                            "sta": "2026-10-01T00:00:00",
                            "stautc": "2026-10-01T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D31302D30317E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-10-01T00:00:00",
                                    "stdutc": "2026-10-01T00:00:00",
                                    "sta": "2026-10-01T00:00:00",
                                    "stautc": "2026-10-01T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-10-01T00:00:00",
                                            "stdutc": "2026-10-01T00:00:00",
                                            "sta": "2026-10-01T00:00:00",
                                            "stautc": "2026-10-01T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 127.53,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 127.53,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443331333032443330333137453334343633343334333333317E"
                        }
                    ]
                },
                {
                    "date": "2026-10-02T00:00:00",
                    "availability": "Available",
                    "journeys": [
                        {
                            "origin": "DUS",
                            "destination": "COV",
                            "std": "2026-10-02T00:00:00",
                            "stdutc": "2026-10-02T00:00:00",
                            "sta": "2026-10-02T00:00:00",
                            "stautc": "2026-10-02T00:00:00",
                            "duration": "00:00:00",
                            "scheduleType": "LowestPrice",
                            "segments": [
                                {
                                    "id": "4455537E434F567E7E7E323032362D31302D30327E344634343331",
                                    "referenceId": "OD1",
                                    "origin": "DUS",
                                    "destination": "COV",
                                    "std": "2026-10-02T00:00:00",
                                    "stdutc": "2026-10-02T00:00:00",
                                    "sta": "2026-10-02T00:00:00",
                                    "stautc": "2026-10-02T00:00:00",
                                    "duration": "00:00:00",
                                    "legs": [
                                        {
                                            "origin": "DUS",
                                            "destination": "COV",
                                            "originTerminal": "",
                                            "destinationTerminal": "",
                                            "std": "2026-10-02T00:00:00",
                                            "stdutc": "2026-10-02T00:00:00",
                                            "sta": "2026-10-02T00:00:00",
                                            "stautc": "2026-10-02T00:00:00",
                                            "duration": "00:00:00",
                                            "legInfo": {
                                                "isSubjectedToGovernmentApproval": false
                                            },
                                            "referenceId": ""
                                        }
                                    ],
                                    "transport": {
                                        "carrier": {
                                            "code": ""
                                        },
                                        "type": "Default",
                                        "number": ""
                                    }
                                }
                            ],
                            "fares": [
                                {
                                    "id": "7E7E7E7E4144547E7E",
                                    "availableSeats": 0,
                                    "paxCode": "ADT",
                                    "serviceBundleCode": "",
                                    "totalAmount": 198.26,
                                    "charges": [
                                        {
                                            "type": "Fare",
                                            "code": "",
                                            "amount": 198.26,
                                            "currency": "USD"
                                        }
                                    ],
                                    "recommended": false
                                }
                            ],
                            "availability": "Available",
                            "openingCheckInDate": "0001-01-01T00:00:00",
                            "closingCheckInDate": "0001-01-01T00:00:00",
                            "id": "3434353535333745343334463536374537453745333233303332333632443331333032443330333237453334343633343334333333317E"
                        }
                    ]
                }
            ]
        }
    ]
}