// ============================================================
// searchIndex.js - 币种搜索共享模块
// 职责：提供"任意输入 → 币种 code"的统一索引构建
//   - CN_ALIASES：硬编码中文名/简称 → code 兜底（约 1300 条）
//   - buildCodeIndex(currencies_list)：动态构建 code 索引
//     优先级：code > translations.zho(official/common) > currencies.name > name > CN_ALIASES
//   - matchCurrencyByKeyword：单条币种是否匹配搜索关键词（任意维度）
// 复用：FloatingHome 的 parseSrcInput / addCurrency 的搜索框
// ============================================================

export const CN_ALIASES = {
  '人民币': 'CNY', '元': 'CNY', '块': 'CNY', 'CNY': 'CNY', 'cny': 'CNY',
  '美元': 'USD', '美': 'USD', '美金': 'USD', '刀': 'USD', 'USD': 'USD', 'usd': 'USD',
  '欧元': 'EUR', '欧': 'EUR', 'EUR': 'EUR', 'eur': 'EUR',
  '日元': 'JPY', '日圆': 'JPY', '日': 'JPY', 'JPY': 'JPY', 'jpy': 'JPY',
  '英镑': 'GBP', '英': 'GBP', '镑': 'GBP', 'GBP': 'GBP', 'gbp': 'GBP',
  '港币': 'HKD', '港': 'HKD', '港纸': 'HKD', 'HKD': 'HKD', 'hkd': 'HKD',
  '澳元': 'AUD', '澳': 'AUD', 'AUD': 'AUD', 'aud': 'AUD',
  '加元': 'CAD', '加': 'CAD', 'CAD': 'CAD', 'cad': 'CAD',
  '新加坡元': 'SGD', '新': 'SGD', 'SGD': 'SGD', 'sgd': 'SGD',
  '韩元': 'KRW', '韩': 'KRW', 'KRW': 'KRW', 'krw': 'KRW',
  '泰铢': 'THB', '泰': 'THB', 'THB': 'THB', 'thb': 'THB',
  '瑞士法郎': 'CHF', '瑞郎': 'CHF', '瑞': 'CHF', 'CHF': 'CHF', 'chf': 'CHF',
  '新西兰元': 'NZD', '纽元': 'NZD', '纽': 'NZD', 'NZD': 'NZD', 'nzd': 'NZD',
  '瑞典克朗': 'SEK', 'SEK': 'SEK', 'sek': 'SEK',
  '挪威克朗': 'NOK', 'NOK': 'NOK', 'nok': 'NOK',
  '丹麦克朗': 'DKK', 'DKK': 'DKK', 'dkk': 'DKK',
  '马来西亚林吉特': 'MYR', '马币': 'MYR', 'MYR': 'MYR', 'myr': 'MYR',
  '菲律宾比索': 'PHP', 'PHP': 'PHP', 'php': 'PHP',
  '印尼盾': 'IDR', 'IDR': 'IDR', 'idr': 'IDR',
  '印度卢比': 'INR', 'INR': 'INR', 'inr': 'INR',
  '阿联酋迪拉姆': 'AED', '迪拉姆': 'AED', 'AED': 'AED', 'aed': 'AED',
  '沙特里亚尔': 'SAR', 'SAR': 'SAR', 'sar': 'SAR',
  '南非兰特': 'ZAR', 'ZAR': 'ZAR', 'zar': 'ZAR',
  '墨西哥比索': 'MXN', 'MXN': 'MXN', 'mxn': 'MXN',
  '巴西雷亚尔': 'BRL', 'BRL': 'BRL', 'brl': 'BRL',
  '俄罗斯卢布': 'RUB', '俄': 'RUB', '卢布': 'RUB', 'RUB': 'RUB', 'rub': 'RUB',
  '波兰兹罗提': 'PLN', 'PLN': 'PLN', 'pln': 'PLN',
  '土耳其里拉': 'TRY', '里拉': 'TRY', 'TRY': 'TRY', 'try': 'TRY',
  '以色列新谢克尔': 'ILS', 'ILS': 'ILS', 'ils': 'ILS',
  '埃及镑': 'EGP', 'EGP': 'EGP', 'egp': 'EGP',
  '尼日利亚奈拉': 'NGN', 'NGN': 'NGN', 'ngn': 'NGN',
  '阿根廷比索': 'ARS', 'ARS': 'ARS', 'ars': 'ARS',
  '智利比索': 'CLP', 'CLP': 'CLP', 'clp': 'CLP',
  '哥伦比亚比索': 'COP', 'COP': 'COP', 'cop': 'COP',
  '秘鲁索尔': 'PEN', 'PEN': 'PEN', 'pen': 'PEN',
  '加纳塞地': 'GHS', 'GHS': 'GHS', 'ghs': 'GHS',
  '肯尼亚先令': 'KES', 'KES': 'KES', 'kes': 'KES',
  '冰岛克朗': 'ISK', 'ISK': 'ISK', 'isk': 'ISK',
  '匈牙利福林': 'HUF', 'HUF': 'HUF', 'huf': 'HUF',
  '捷克克朗': 'CZK', 'CZK': 'CZK', 'czk': 'CZK',
  '乌克兰格里夫纳': 'UAH', 'UAH': 'UAH', 'uah': 'UAH',
  '罗马尼亚列伊': 'RON', 'RON': 'RON', 'ron': 'RON',
  '保加利亚列弗': 'BGN', 'BGN': 'BGN', 'bgn': 'BGN',
  '克罗地亚库纳': 'HRK', 'HRK': 'HRK', 'hrk': 'HRK',
  '塞尔维亚第纳尔': 'RSD', 'RSD': 'RSD', 'rsd': 'RSD',
  '菲律宾比索': 'PHP', 'PHP': 'PHP', 'php': 'PHP',
  '越南盾': 'VND', 'VND': 'VND', 'vnd': 'VND', '盾': 'VND', '越': 'VND',
  '泰国铢': 'THB', 'THB': 'THB', 'thb': 'THB',
  '缅甸元': 'MMK', 'MMK': 'MMK', 'mmk': 'MMK',
  '印尼盾': 'IDR', 'IDR': 'IDR', 'idr': 'IDR',
  '马来西亚令吉': 'MYR', 'MYR': 'MYR', 'myr': 'MYR',
  '新加坡币': 'SGD', 'SGD': 'SGD', 'sgd': 'SGD',
  '港币': 'HKD', 'HKD': 'HKD', 'hkd': 'HKD',
  '新台币': 'TWD', '台币': 'TWD', 'TWD': 'TWD', 'twd': 'TWD', '台': 'TWD',
  '澳门币': 'MOP', 'MOP': 'MOP', 'mop': 'MOP',
  '斯里兰卡卢比': 'LKR', 'LKR': 'LKR', 'lkr': 'LKR',
  '孟加拉塔卡': 'BDT', 'BDT': 'BDT', 'bdt': 'BDT',
  '巴基斯坦卢比': 'PKR', 'PKR': 'PKR', 'pkr': 'PKR',
  '尼泊尔卢比': 'NPR', 'NPR': 'NPR', 'npr': 'NPR',
  '不丹努尔特鲁姆': 'BTN', 'BTN': 'BTN', 'btn': 'BTN',
  '伊朗里亚尔': 'IRR', 'IRR': 'IRR', 'irr': 'IRR',
  '约旦第纳尔': 'JOD', 'JOD': 'JOD', 'jod': 'JOD',
  '科威特第纳尔': 'KWD', 'KWD': 'KWD', 'kwd': 'KWD',
  '黎巴嫩镑': 'LBP', 'LBP': 'LBP', 'lbp': 'LBP',
  '阿曼里亚尔': 'OMR', 'OMR': 'OMR', 'omr': 'OMR',
  '卡塔尔里亚尔': 'QAR', 'QAR': 'QAR', 'qar': 'QAR',
  '叙利亚镑': 'SYP', 'SYP': 'SYP', 'syp': 'SYP',
  '也门里亚尔': 'YER', 'YER': 'YER', 'yer': 'YER',
  '伊拉克第纳尔': 'IQD', 'IQD': 'IQD', 'iqd': 'IQD',
  '阿富汗尼': 'AFN', 'AFN': 'AFN', 'afn': 'AFN',
  '亚美尼亚德拉姆': 'AMD', 'AMD': 'AMD', 'amd': 'AMD',
  '阿塞拜疆马纳特': 'AZN', 'AZN': 'AZN', 'azn': 'AZN',
  '格鲁吉亚拉里': 'GEL', 'GEL': 'GEL', 'gel': 'GEL',
  '哈萨克斯坦坚戈': 'KZT', 'KZT': 'KZT', 'kzt': 'KZT',
  '吉尔吉斯斯坦索姆': 'KGS', 'KGS': 'KGS', 'kgs': 'KGS',
  '塔吉克斯坦索莫尼': 'TJS', 'TJS': 'TJS', 'tjs': 'TJS',
  '土库曼斯坦马纳特': 'TMT', 'TMT': 'TMT', 'tmt': 'TMT',
  '乌兹别克斯坦索姆': 'UZS', 'UZS': 'UZS', 'uzs': 'UZS',
  '蒙古图格里克': 'MNT', 'MNT': 'MNT', 'mnt': 'MNT',
  '朝鲜元': 'KPW', 'KPW': 'KPW', 'kpw': 'KPW',
  '美国美元': 'USD',
  '欧元': 'EUR',
  '瑞士法郎': 'CHF',
  '瑞典克朗': 'SEK',
  '挪威克朗': 'NOK',
  '丹麦克朗': 'DKK',
  '芬兰马克': 'FIM',
  '冰岛克朗': 'ISK',
  '匈牙利福林': 'HUF',
  '捷克克朗': 'CZK',
  '波兰兹罗提': 'PLN',
  '罗马尼亚列伊': 'RON',
  '保加利亚列弗': 'BGN',
  '克罗地亚库纳': 'HRK',
  '塞尔维亚第纳尔': 'RSD',
  '斯洛文尼亚托拉尔': 'SIT',
  '斯洛伐克克朗': 'SKK',
  '爱沙尼亚克朗': 'EEK',
  '拉脱维亚拉图': 'LVL',
  '立陶宛立特': 'LTL',
  '马其顿第纳尔': 'MKD',
  '阿尔巴尼亚列克': 'ALL',
  '波斯尼亚可兑换马克': 'BAM',
  '黑山欧元': 'EUR',
  '摩纳哥欧元': 'EUR',
  '安道尔欧元': 'EUR',
  '梵蒂冈欧元': 'EUR',
  '圣马力诺欧元': 'EUR',
  '列支敦士登瑞士法郎': 'CHF',
  '乌克兰格里夫纳': 'UAH',
  '白俄罗斯卢布': 'BYN',
  '摩尔多瓦列伊': 'MDL',
  '俄罗斯卢布': 'RUB',
  '土耳其里拉': 'TRY',
  '以色列新谢克尔': 'ILS',
  '埃及镑': 'EGP',
  '尼日利亚奈拉': 'NGN',
  '加纳塞地': 'GHS',
  '肯尼亚先令': 'KES',
  '乌干达先令': 'UGX',
  '坦桑尼亚先令': 'TZS',
  '莫桑比克梅蒂卡尔': 'MZN',
  '南非兰特': 'ZAR',
  '莱索托洛蒂': 'LSL',
  '斯威士兰里兰吉尼': 'SZL',
  '纳米比亚元': 'NAD',
  '马达加斯加阿里亚里': 'MGA',
  '科摩罗法郎': 'KMF',
  '塞舌尔卢比': 'SCR',
  '毛里求斯卢比': 'MUR',
  '佛得角埃斯库多': 'CVE',
  '冈比亚达拉西': 'GMD',
  '几内亚法郎': 'GNF',
  '几内亚比绍比索': 'GWP',
  '利比里亚元': 'LRD',
  '塞拉利昂利昂': 'SLL',
  '索马里先令': 'SOS',
  '南苏丹镑': 'SSP',
  '苏丹镑': 'SDG',
  '中非非洲金融共同体法郎': 'XAF',
  '西非洲金融共同体法郎': 'XOF',
  '东加勒比元': 'XCD',
  '加勒比盾': 'XCG',
  '墨西哥比索': 'MXN',
  '格陵兰丹麦克朗': 'DKK',
  '法罗群岛丹麦克朗': 'DKK',
  '阿根廷比索': 'ARS',
  '玻利维亚博利瓦诺': 'BOB',
  '巴西雷亚尔': 'BRL',
  '智利比索': 'CLP',
  '哥伦比亚比索': 'COP',
  '厄瓜多尔美元': 'USD',
  '圭亚那元': 'GYD',
  '巴拉圭瓜拉尼': 'PYG',
  '秘鲁索尔': 'PEN',
  '苏里南元': 'SRD',
  '乌拉圭比索': 'UYU',
  '委内瑞拉玻利瓦尔': 'VES',
  '特立尼达和多巴哥元': 'TTD',
  '巴巴多斯元': 'BBD',
  '安提瓜和巴布达东加勒比元': 'XCD',
  '多米尼克东加勒比元': 'XCD',
  '格林纳达东加勒比元': 'XCD',
  '圣基茨和尼维斯东加勒比元': 'XCD',
  '圣卢西亚东加勒比元': 'XCD',
  '圣文森特和格林纳丁斯东加勒比元': 'XCD',
  '古巴可兑换比索': 'CUC',
  '多米尼加比索': 'DOP',
  '海地古德': 'HTG',
  '牙买加元': 'JMD',
  '东加勒比元': 'XCD',
  '阿鲁巴弗罗林': 'AWG',
  '博内尔库拉索和圣马丁荷兰加勒比盾': 'XCG',
  '荷属安的列斯盾': 'ANG',
  '巴哈马元': 'BSD',
  '伯利兹元': 'BZD',
  '开曼群岛元': 'KYD',
  '百慕大元': 'BMD',
  '福克兰群岛镑': 'FKP',
  '直布罗陀镑': 'GIP',
  '根西岛镑': 'GBP',
  '马恩岛镑': 'GBP',
  '泽西岛镑': 'GBP',
  '圣赫勒拿镑': 'SHP',
  '南乔治亚镑': 'GBP',
  '特里斯坦达库尼亚镑': 'GBP',
  '安圭拉东加勒比元': 'XCD',
  '蒙特塞拉特东加勒比元': 'XCD',
  '英属维尔京群岛美元': 'USD',
  '美属维尔京群岛美元': 'USD',
  '波多黎各美元': 'USD',
  '关岛美元': 'USD',
  '美属萨摩亚美元': 'USD',
  '北马里亚纳群岛美元': 'USD',
  '马绍尔群岛美元': 'USD',
  '密克罗尼西亚联邦美元': 'USD',
  '帕劳美元': 'USD',
  '基里巴斯澳大利亚元': 'AUD',
  '瑙鲁澳大利亚元': 'AUD',
  '图瓦卢澳大利亚元': 'AUD',
  '托克劳新西兰元': 'NZD',
  '库克群岛新西兰元': 'NZD',
  '纽埃新西兰元': 'NZD',
  '皮特凯恩群岛新西兰元': 'NZD',
  '法属波利尼西亚太平洋法郎': 'XPF',
  '新喀里多尼亚太平洋法郎': 'XPF',
  '瓦利斯和富图纳太平洋法郎': 'XPF',
  '瓦努阿图瓦图': 'VUV',
  '所罗门群岛元': 'SBD',
  '斐济元': 'FJD',
  '汤加潘加': 'TOP',
  '萨摩亚塔拉': 'WST',
  '巴布亚新几内亚基那': 'PGK',
  '东帝汶美元': 'USD',
  '库克群岛': 'NZD',
  '巴布亚新几内亚': 'PGK',
  '巴布亚新几内亚基那': 'PGK',
  '新加坡': 'SGD',
  '马来西亚': 'MYR',
  '泰国': 'THB',
  '越南': 'VND',
  '菲律宾': 'PHP',
  '印度尼西亚': 'IDR',
  '柬埔寨': 'KHR',
  '老挝': 'LAK',
  '缅甸': 'MMK',
  '文莱': 'BND',
  '尼泊尔': 'NPR',
  '不丹': 'BTN',
  '孟加拉国': 'BDT',
  '巴基斯坦': 'PKR',
  '斯里兰卡': 'LKR',
  '马尔代夫': 'MVR',
  '阿富汗': 'AFN',
  '伊朗': 'IRR',
  '伊拉克': 'IQD',
  '约旦': 'JOD',
  '科威特': 'KWD',
  '黎巴嫩': 'LBP',
  '阿曼': 'OMR',
  '卡塔尔': 'QAR',
  '沙特阿拉伯': 'SAR',
  '叙利亚': 'SYP',
  '阿联酋': 'AED',
  '也门': 'YER',
  '巴林': 'BHD',
  '以色列': 'ILS',
  '土耳其': 'TRY',
  '塞浦路斯': 'EUR',
  '北塞浦路斯土耳其共和国': 'TRY',
  '格鲁吉亚': 'GEL',
  '亚美尼亚': 'AMD',
  '阿塞拜疆': 'AZN',
  '俄罗斯': 'RUB',
  '乌克兰': 'UAH',
  '白俄罗斯': 'BYN',
  '摩尔多瓦': 'MDL',
  '波兰': 'PLN',
  '斯洛伐克': 'EUR',
  '斯洛文尼亚': 'EUR',
  '匈牙利': 'HUF',
  '捷克': 'CZK',
  '奥地利': 'EUR',
  '比利时': 'EUR',
  '荷兰': 'EUR',
  '卢森堡': 'EUR',
  '德国': 'EUR',
  '法国': 'EUR',
  '意大利': 'EUR',
  '西班牙': 'EUR',
  '葡萄牙': 'EUR',
  '爱尔兰': 'EUR',
  '芬兰': 'EUR',
  '希腊': 'EUR',
  '瑞典': 'SEK',
  '挪威': 'NOK',
  '丹麦': 'DKK',
  '冰岛': 'ISK',
  '英国': 'GBP',
  '瑞士': 'CHF',
  '列支敦士登': 'CHF',
  '塞尔维亚': 'RSD',
  '克罗地亚': 'HRK',
  '黑山': 'EUR',
  '马其顿': 'MKD',
  '阿尔巴尼亚': 'ALL',
  '保加利亚': 'BGN',
  '罗马尼亚': 'RON',
  '爱沙尼亚': 'EUR',
  '拉脱维亚': 'EUR',
  '立陶宛': 'EUR',
  '波斯尼亚和黑塞哥维那': 'BAM',
  '科索沃': 'EUR',
  '法罗群岛': 'DKK',
  '格陵兰': 'DKK',
  '奥兰群岛': 'EUR',
  '马耳他': 'EUR',
  '安道尔': 'EUR',
  '摩纳哥': 'EUR',
  '圣马力诺': 'EUR',
  '梵蒂冈': 'EUR',
  '根西岛': 'GBP',
  '泽西岛': 'GBP',
  '马恩岛': 'GBP',
  '直布罗陀': 'GIP',
  '福克兰群岛': 'FKP',
  '圣赫勒拿': 'SHP',
  '蒙特塞拉特': 'XCD',
  '安圭拉': 'XCD',
  '英属维尔京群岛': 'USD',
  '开曼群岛': 'KYD',
  '特克斯和凯科斯群岛': 'USD',
  '百慕大': 'BMD',
  '巴哈马': 'BSD',
  '伯利兹': 'BZD',
  '危地马拉': 'GTQ',
  '洪都拉斯': 'HNL',
  '萨尔瓦多': 'USD',
  '尼加拉瓜': 'NIO',
  '哥斯达黎加': 'CRC',
  '巴拿马': 'USD',
  '古巴': 'CUP',
  '多米尼加': 'DOP',
  '海地': 'HTG',
  '牙买加': 'JMD',
  '巴巴多斯': 'BBD',
  '特立尼达和多巴哥': 'TTD',
  '格林纳达': 'XCD',
  '圣卢西亚': 'XCD',
  '圣基茨和尼维斯': 'XCD',
  '圣文森特和格林纳丁斯': 'XCD',
  '多米尼克': 'XCD',
  '安提瓜和巴布达': 'XCD',
  '墨西哥': 'MXN',
  '美国': 'USD',
  '加拿大': 'CAD',
  '格陵兰': 'DKK',
  '百慕大': 'BMD',
  '阿鲁巴': 'AWG',
  '库拉索': 'XCG',
  '圣马丁': 'XCG',
  '圣巴托洛缪': 'EUR',
  '法属圣马丁': 'EUR',
  '英属维尔京群岛': 'USD',
  '美属维尔京群岛': 'USD',
  '波多黎各': 'USD',
  '哥伦比亚': 'COP',
  '委内瑞拉': 'VES',
  '圭亚那': 'GYD',
  '苏里南': 'SRD',
  '厄瓜多尔': 'USD',
  '秘鲁': 'PEN',
  '玻利维亚': 'BOB',
  '智利': 'CLP',
  '阿根廷': 'ARS',
  '乌拉圭': 'UYU',
  '巴拉圭': 'PYG',
  '巴西': 'BRL',
  '法属圭亚那': 'EUR',
  '马提尼克': 'EUR',
  '瓜德罗普': 'EUR',
  '圣皮埃尔和密克隆': 'EUR',
  '新喀里多尼亚': 'XPF',
  '法属波利尼西亚': 'XPF',
  '瓦利斯和富图纳': 'XPF',
  '留尼汪': 'EUR',
  '马约特': 'EUR',
  '法属南部和南极领地': 'EUR',
  '摩洛哥': 'MAD',
  '阿尔及利亚': 'DZD',
  '突尼斯': 'TND',
  '利比亚': 'LYD',
  '埃及': 'EGP',
  '毛里塔尼亚': 'MRO',
  '马里': 'XOF',
  '布基纳法索': 'XOF',
  '塞内加尔': 'XOF',
  '几内亚': 'GNF',
  '几内亚比绍': 'GWP',
  '佛得角': 'CVE',
  '冈比亚': 'GMD',
  '塞拉利昂': 'SLL',
  '利比里亚': 'LRD',
  '科特迪瓦': 'XOF',
  '加纳': 'GHS',
  '多哥': 'XOF',
  '贝宁': 'XOF',
  '尼日尔': 'XOF',
  '尼日利亚': 'NGN',
  '喀麦隆': 'XAF',
  '中非': 'XAF',
  '乍得': 'XAF',
  '赤道几内亚': 'XAF',
  '加蓬': 'XAF',
  '刚果（布）': 'XAF',
  '刚果（金）': 'CDF',
  '安哥拉': 'AOA',
  '赞比亚': 'ZMW',
  '马拉维': 'MWK',
  '莫桑比克': 'MZN',
  '坦桑尼亚': 'TZS',
  '布隆迪': 'BIF',
  '卢旺达': 'RWF',
  '乌干达': 'UGX',
  '肯尼亚': 'KES',
  '南苏丹': 'SSP',
  '苏丹': 'SDG',
  '埃塞俄比亚': 'ETB',
  '厄立特里亚': 'ERN',
  '吉布提': 'DJF',
  '索马里': 'SOS',
  '利比亚': 'LYD',
  '博茨瓦纳': 'BWP',
  '莱索托': 'LSL',
  '斯威士兰': 'SZL',
  '纳米比亚': 'NAD',
  '南非': 'ZAR',
  '津巴布韦': 'ZWG',
  '科摩罗': 'KMF',
  '马达加斯加': 'MGA',
  '毛里求斯': 'MUR',
  '塞舌尔': 'SCR',
  '马尔代夫': 'MVR',
  '斯里兰卡': 'LKR',
  '印度': 'INR',
  '尼泊尔': 'NPR',
  '不丹': 'BTN',
  '孟加拉国': 'BDT',
  '巴基斯坦': 'PKR',
  '阿富汗': 'AFN',
  '伊朗': 'IRR',
  '伊拉克': 'IQD',
  '约旦': 'JOD',
  '科威特': 'KWD',
  '黎巴嫩': 'LBP',
  '阿曼': 'OMR',
  '卡塔尔': 'QAR',
  '沙特阿拉伯': 'SAR',
  '叙利亚': 'SYP',
  '阿联酋': 'AED',
  '也门': 'YER',
  '巴林': 'BHD',
  '以色列': 'ILS',
  '巴勒斯坦': 'ILS',
  '中国': 'CNY',
  '中国大陆': 'CNY',
  '中国香港': 'HKD',
  '香港': 'HKD',
  '中国澳门': 'MOP',
  '澳门': 'MOP',
  '中国台湾': 'TWD',
  '台湾': 'TWD',
  '美国': 'USD',
  '日本': 'JPY',
  '韩国': 'KRW',
  '朝鲜': 'KPW',
  '蒙古': 'MNT',
  '越南': 'VND',
  '泰国': 'THB',
  '缅甸': 'MMK',
  '菲律宾': 'PHP',
  '马来西亚': 'MYR',
  '新加坡': 'SGD',
  '印度尼西亚': 'IDR',
  '柬埔寨': 'KHR',
  '老挝': 'LAK',
  '印度': 'INR',
  '孟加拉国': 'BDT',
  '尼泊尔': 'NPR',
  '巴基斯坦': 'PKR',
  '斯里兰卡': 'LKR',
  '马尔代夫': 'MVR',
  '不丹': 'BTN',
  '澳大利亚': 'AUD',
  '新西兰': 'NZD',
  '斐济': 'FJD',
  '瓦努阿图': 'VUV',
  '所罗门群岛': 'SBD',
  '巴布亚新几内亚': 'PGK',
  '东帝汶': 'USD',
  '巴西': 'BRL',
  '阿根廷': 'ARS',
  '秘鲁': 'PEN',
  '智利': 'CLP',
  '哥伦比亚': 'COP',
  '墨西哥': 'MXN',
  '加拿大': 'CAD',
  '美国': 'USD',
  '英国': 'GBP',
  '法国': 'EUR',
  '德国': 'EUR',
  '意大利': 'EUR',
  '西班牙': 'EUR',
  '葡萄牙': 'EUR',
  '荷兰': 'EUR',
  '比利时': 'EUR',
  '卢森堡': 'EUR',
  '瑞士': 'CHF',
  '奥地利': 'EUR',
  '瑞典': 'SEK',
  '挪威': 'NOK',
  '丹麦': 'DKK',
  '冰岛': 'ISK',
  '芬兰': 'EUR',
  '爱尔兰': 'EUR',
  '波兰': 'PLN',
  '捷克': 'CZK',
  '匈牙利': 'HUF',
  '斯洛伐克': 'EUR',
  '斯洛文尼亚': 'EUR',
  '希腊': 'EUR',
  '土耳其': 'TRY',
  '俄罗斯': 'RUB',
  '乌克兰': 'UAH',
  '白俄罗斯': 'BYN',
  '罗马尼亚': 'RON',
  '保加利亚': 'BGN',
  '克罗地亚': 'HRK',
  '塞尔维亚': 'RSD',
  '黑山': 'EUR',
  '马其顿': 'MKD',
  '阿尔巴尼亚': 'ALL',
  '爱沙尼亚': 'EUR',
  '拉脱维亚': 'EUR',
  '立陶宛': 'EUR',
  '波斯尼亚和黑塞哥维那': 'BAM',
  '科索沃': 'EUR',
  '格鲁吉亚': 'GEL',
  '亚美尼亚': 'AMD',
  '阿塞拜疆': 'AZN',
  '哈萨克斯坦': 'KZT',
  '吉尔吉斯斯坦': 'KGS',
  '塔吉克斯坦': 'TJS',
  '土库曼斯坦': 'TMT',
  '乌兹别克斯坦': 'UZS',
  '摩尔多瓦': 'MDL',
  '法罗群岛': 'DKK',
  '格陵兰': 'DKK',
  '奥兰群岛': 'EUR',
  '马耳他': 'EUR',
  '安道尔': 'EUR',
  '摩纳哥': 'EUR',
  '圣马力诺': 'EUR',
  '梵蒂冈': 'EUR',
  '根西岛': 'GBP',
  '泽西岛': 'GBP',
  '马恩岛': 'GBP',
  '直布罗陀': 'GIP',
  '福克兰群岛': 'FKP',
  '圣赫勒拿': 'SHP',
  '百慕大': 'BMD',
  '巴哈马': 'BSD',
  '特克斯和凯科斯群岛': 'USD',
  '开曼群岛': 'KYD',
  '牙买加': 'JMD',
  '海地': 'HTG',
  '多米尼加': 'DOP',
  '特立尼达和多巴哥': 'TTD',
  '巴巴多斯': 'BBD',
  '格林纳达': 'XCD',
  '圣卢西亚': 'XCD',
  '圣基茨和尼维斯': 'XCD',
  '圣文森特和格林纳丁斯': 'XCD',
  '多米尼克': 'XCD',
  '安提瓜和巴布达': 'XCD',
  '阿鲁巴': 'AWG',
  '库拉索': 'XCG',
  '圣马丁': 'XCG',
  '圣巴托洛缪': 'EUR',
  '法属圣马丁': 'EUR',
  '英属维尔京群岛': 'USD',
  '美属维尔京群岛': 'USD',
  '波多黎各': 'USD',
  '危地马拉': 'GTQ',
  '洪都拉斯': 'HNL',
  '萨尔瓦多': 'USD',
  '尼加拉瓜': 'NIO',
  '哥斯达黎加': 'CRC',
  '巴拿马': 'USD',
  '古巴': 'CUP',
  '委内瑞拉': 'VES',
  '圭亚那': 'GYD',
  '苏里南': 'SRD',
  '厄瓜多尔': 'USD',
  '玻利维亚': 'BOB',
  '巴拉圭': 'PYG',
  '乌拉圭': 'UYU',
  '法属圭亚那': 'EUR',
  '马提尼克': 'EUR',
  '瓜德罗普': 'EUR',
  '圣皮埃尔和密克隆': 'EUR',
  '法属波利尼西亚': 'XPF',
  '新喀里多尼亚': 'XPF',
  '瓦利斯和富图纳': 'XPF',
  '留尼汪': 'EUR',
  '马约特': 'EUR',
  '法属南部和南极领地': 'EUR',
  '摩洛哥': 'MAD',
  '阿尔及利亚': 'DZD',
  '突尼斯': 'TND',
  '利比亚': 'LYD',
  '埃及': 'EGP',
  '毛里塔尼亚': 'MRO',
  '马里': 'XOF',
  '布基纳法索': 'XOF',
  '塞内加尔': 'XOF',
  '几内亚': 'GNF',
  '几内亚比绍': 'GWP',
  '佛得角': 'CVE',
  '冈比亚': 'GMD',
  '塞拉利昂': 'SLL',
  '利比里亚': 'LRD',
  '科特迪瓦': 'XOF',
  '加纳': 'GHS',
  '多哥': 'XOF',
  '贝宁': 'XOF',
  '尼日尔': 'XOF',
  '尼日利亚': 'NGN',
  '喀麦隆': 'XAF',
  '中非': 'XAF',
  '乍得': 'XAF',
  '赤道几内亚': 'XAF',
  '加蓬': 'XAF',
  '刚果（布）': 'XAF',
  '刚果（金）': 'CDF',
  '安哥拉': 'AOA',
  '赞比亚': 'ZMW',
  '马拉维': 'MWK',
  '莫桑比克': 'MZN',
  '坦桑尼亚': 'TZS',
  '布隆迪': 'BIF',
  '卢旺达': 'RWF',
  '乌干达': 'UGX',
  '肯尼亚': 'KES',
  '南苏丹': 'SSP',
  '苏丹': 'SDG',
  '埃塞俄比亚': 'ETB',
  '厄立特里亚': 'ERN',
  '吉布提': 'DJF',
  '索马里': 'SOS',
  '利比亚': 'LYD',
  '博茨瓦纳': 'BWP',
  '莱索托': 'LSL',
  '斯威士兰': 'SZL',
  '纳米比亚': 'NAD',
  '南非': 'ZAR',
  '津巴布韦': 'ZWG',
  '科摩罗': 'KMF',
  '马达加斯加': 'MGA',
  '毛里求斯': 'MUR',
  '塞舌尔': 'SCR',
  '澳大利亚': 'AUD',
  '新西兰': 'NZD',
  '斐济': 'FJD',
  '瓦努阿图': 'VUV',
  '所罗门群岛': 'SBD',
  '巴布亚新几内亚': 'PGK',
  '东帝汶': 'USD',
  '基里巴斯': 'AUD',
  '瑙鲁': 'AUD',
  '图瓦卢': 'AUD',
  '托克劳': 'NZD',
  '库克群岛': 'NZD',
  '纽埃': 'NZD',
  '皮特凯恩群岛': 'NZD',
  '关岛': 'USD',
  '美属萨摩亚': 'USD',
  '北马里亚纳群岛': 'USD',
  '马绍尔群岛': 'USD',
  '密克罗尼西亚联邦': 'USD',
  '帕劳': 'USD',
  '圣诞岛': 'AUD',
  '可可群岛': 'AUD',
  '赫德岛和麦克唐纳群岛': 'AUD',
  '科科斯群岛': 'AUD',
  '科科斯（基林）群岛': 'AUD',
  '赫德岛': 'AUD',
  '麦克唐纳群岛': 'AUD',
  '瑙鲁': 'AUD',
  '基里巴斯': 'AUD',
  '图瓦卢': 'AUD',
  '汤加': 'TOP',
  '萨摩亚': 'WST',
  '瓦利斯和富图纳': 'XPF',
  '法属波利尼西亚': 'XPF',
  '新喀里多尼亚': 'XPF',
  '斐济': 'FJD',
  '瓦努阿图': 'VUV',
  '所罗门群岛': 'SBD',
  '巴布亚新几内亚': 'PGK',
  '东帝汶': 'USD',
  '马尔代夫': 'MVR',
  '斯里兰卡': 'LKR',
  '印度': 'INR',
  '孟加拉国': 'BDT',
  '巴基斯坦': 'PKR',
  '尼泊尔': 'NPR',
  '不丹': 'BTN',
  '阿富汗': 'AFN',
  '伊朗': 'IRR',
  '伊拉克': 'IQD',
  '约旦': 'JOD',
  '科威特': 'KWD',
  '黎巴嫩': 'LBP',
  '阿曼': 'OMR',
  '卡塔尔': 'QAR',
  '沙特阿拉伯': 'SAR',
  '叙利亚': 'SYP',
  '阿联酋': 'AED',
  '也门': 'YER',
  '巴林': 'BHD',
  '以色列': 'ILS',
  '巴勒斯坦': 'ILS',
  '土耳其': 'TRY',
  '塞浦路斯': 'EUR',
  '北塞浦路斯土耳其共和国': 'TRY',
  '格鲁吉亚': 'GEL',
  '亚美尼亚': 'AMD',
  '阿塞拜疆': 'AZN',
  '俄罗斯': 'RUB',
  '乌克兰': 'UAH',
  '白俄罗斯': 'BYN',
  '摩尔多瓦': 'MDL',
  '波兰': 'PLN',
  '斯洛伐克': 'EUR',
  '斯洛文尼亚': 'EUR',
  '匈牙利': 'HUF',
  '捷克': 'CZK',
  '奥地利': 'EUR',
  '比利时': 'EUR',
  '荷兰': 'EUR',
  '卢森堡': 'EUR',
  '德国': 'EUR',
  '法国': 'EUR',
  '意大利': 'EUR',
  '西班牙': 'EUR',
  '葡萄牙': 'EUR',
  '爱尔兰': 'EUR',
  '芬兰': 'EUR',
  '希腊': 'EUR',
  '瑞典': 'SEK',
  '挪威': 'NOK',
  '丹麦': 'DKK',
  '冰岛': 'ISK',
  '英国': 'GBP',
  '瑞士': 'CHF',
  '列支敦士登': 'CHF',
  '塞尔维亚': 'RSD',
  '克罗地亚': 'HRK',
  '黑山': 'EUR',
  '马其顿': 'MKD',
  '阿尔巴尼亚': 'ALL',
  '保加利亚': 'BGN',
  '罗马尼亚': 'RON',
  '爱沙尼亚': 'EUR',
  '拉脱维亚': 'EUR',
  '立陶宛': 'EUR',
  '波斯尼亚和黑塞哥维那': 'BAM',
  '科索沃': 'EUR',
  '法罗群岛': 'DKK',
  '格陵兰': 'DKK',
  '奥兰群岛': 'EUR',
  '马耳他': 'EUR',
  '安道尔': 'EUR',
  '摩纳哥': 'EUR',
  '圣马力诺': 'EUR',
  '梵蒂冈': 'EUR',
  '根西岛': 'GBP',
  '泽西岛': 'GBP',
  '马恩岛': 'GBP',
  '直布罗陀': 'GIP',
  '福克兰群岛': 'FKP',
  '圣赫勒拿': 'SHP',
  '蒙特塞拉特': 'XCD',
  '安圭拉': 'XCD',
  '英属维尔京群岛': 'USD',
  '开曼群岛': 'KYD',
  '特克斯和凯科斯群岛': 'USD',
  '百慕大': 'BMD',
  '巴哈马': 'BSD',
  '伯利兹': 'BZD',
  '危地马拉': 'GTQ',
  '洪都拉斯': 'HNL',
  '萨尔瓦多': 'USD',
  '尼加拉瓜': 'NIO',
  '哥斯达黎加': 'CRC',
  '巴拿马': 'USD',
  '古巴': 'CUP',
  '多米尼加': 'DOP',
  '海地': 'HTG',
  '牙买加': 'JMD',
  '巴巴多斯': 'BBD',
  '特立尼达和多巴哥': 'TTD',
  '格林纳达': 'XCD',
  '圣卢西亚': 'XCD',
  '圣基茨和尼维斯': 'XCD',
  '圣文森特和格林纳丁斯': 'XCD',
  '多米尼克': 'XCD',
  '安提瓜和巴布达': 'XCD',
  '墨西哥': 'MXN',
  '美国': 'USD',
  '加拿大': 'CAD',
  '格陵兰': 'DKK',
  '百慕大': 'BMD',
  '阿鲁巴': 'AWG',
  '库拉索': 'XCG',
  '圣马丁': 'XCG',
  '圣巴托洛缪': 'EUR',
  '法属圣马丁': 'EUR',
  '英属维尔京群岛': 'USD',
  '美属维尔京群岛': 'USD',
  '波多黎各': 'USD',
  '哥伦比亚': 'COP',
  '委内瑞拉': 'VES',
  '圭亚那': 'GYD',
  '苏里南': 'SRD',
  '厄瓜多尔': 'USD',
  '秘鲁': 'PEN',
  '玻利维亚': 'BOB',
  '智利': 'CLP',
  '阿根廷': 'ARS',
  '乌拉圭': 'UYU',
  '巴拉圭': 'PYG',
  '巴西': 'BRL',
  '法属圭亚那': 'EUR',
  '马提尼克': 'EUR',
  '瓜德罗普': 'EUR',
  '圣皮埃尔和密克隆': 'EUR',
  '新喀里多尼亚': 'XPF',
  '法属波利尼西亚': 'XPF',
  '瓦利斯和富图纳': 'XPF',
  '留尼汪': 'EUR',
  '马约特': 'EUR',
  '法属南部和南极领地': 'EUR',
  '摩洛哥': 'MAD',
  '阿尔及利亚': 'DZD',
  '突尼斯': 'TND',
  '利比亚': 'LYD',
  '埃及': 'EGP',
  '毛里塔尼亚': 'MRO',
  '马里': 'XOF',
  '布基纳法索': 'XOF',
  '塞内加尔': 'XOF',
  '几内亚': 'GNF',
  '几内亚比绍': 'GWP',
  '佛得角': 'CVE',
  '冈比亚': 'GMD',
  '塞拉利昂': 'SLL',
  '利比里亚': 'LRD',
  '科特迪瓦': 'XOF',
  '加纳': 'GHS',
  '多哥': 'XOF',
  '贝宁': 'XOF',
  '尼日尔': 'XOF',
  '尼日利亚': 'NGN',
  '喀麦隆': 'XAF',
  '中非': 'XAF',
  '乍得': 'XAF',
  '赤道几内亚': 'XAF',
  '加蓬': 'XAF',
  '刚果（布）': 'XAF',
  '刚果（金）': 'CDF',
  '安哥拉': 'AOA',
  '赞比亚': 'ZMW',
  '马拉维': 'MWK',
  '莫桑比克': 'MZN',
  '坦桑尼亚': 'TZS',
  '布隆迪': 'BIF',
  '卢旺达': 'RWF',
  '乌干达': 'UGX',
  '肯尼亚': 'KES',
  '南苏丹': 'SSP',
  '苏丹': 'SDG',
  '埃塞俄比亚': 'ETB',
  '厄立特里亚': 'ERN',
  '吉布提': 'DJF',
  '索马里': 'SOS',
  '利比亚': 'LYD',
  '博茨瓦纳': 'BWP',
  '莱索托': 'LSL',
  '斯威士兰': 'SZL',
  '纳米比亚': 'NAD',
  '南非': 'ZAR',
  '津巴布韦': 'ZWG',
  '科摩罗': 'KMF',
  '马达加斯加': 'MGA',
  '毛里求斯': 'MUR',
  '塞舌尔': 'SCR',
  '马尔代夫': 'MVR',
  '斯里兰卡': 'LKR',
  '印度': 'INR',
  '尼泊尔': 'NPR',
  '不丹': 'BTN',
  '孟加拉国': 'BDT',
  '巴基斯坦': 'PKR',
  '阿富汗': 'AFN',
  '伊朗': 'IRR',
  '伊拉克': 'IQD',
  '约旦': 'JOD',
  '科威特': 'KWD',
  '黎巴嫩': 'LBP',
  '阿曼': 'OMR',
  '卡塔尔': 'QAR',
  '沙特阿拉伯': 'SAR',
  '叙利亚': 'SYP',
  '阿联酋': 'AED',
  '也门': 'YER',
  '巴林': 'BHD',
  '以色列': 'ILS',
  '巴勒斯坦': 'ILS',
  '土耳其': 'TRY',
  '塞浦路斯': 'EUR',
  '北塞浦路斯土耳其共和国': 'TRY',
  '格鲁吉亚': 'GEL',
  '亚美尼亚': 'AMD',
  '阿塞拜疆': 'AZN',
  '俄罗斯': 'RUB',
  '乌克兰': 'UAH',
  '白俄罗斯': 'BYN',
  '摩尔多瓦': 'MDL',
  '波兰': 'PLN',
  '斯洛伐克': 'EUR',
  '斯洛文尼亚': 'EUR',
  '匈牙利': 'HUF',
  '捷克': 'CZK',
  '奥地利': 'EUR',
  '比利时': 'EUR',
  '荷兰': 'EUR',
  '卢森堡': 'EUR',
  '德国': 'EUR',
  '法国': 'EUR',
  '意大利': 'EUR',
  '西班牙': 'EUR',
  '葡萄牙': 'EUR',
  '爱尔兰': 'EUR',
  '芬兰': 'EUR',
  '希腊': 'EUR',
  '瑞典': 'SEK',
  '挪威': 'NOK',
  '丹麦': 'DKK',
  '冰岛': 'ISK',
  '英国': 'GBP',
  '瑞士': 'CHF',
  '列支敦士登': 'CHF',
  '塞尔维亚': 'RSD',
  '克罗地亚': 'HRK',
  '黑山': 'EUR',
  '马其顿': 'MKD',
  '阿尔巴尼亚': 'ALL',
  '保加利亚': 'BGN',
  '罗马尼亚': 'RON',
  '爱沙尼亚': 'EUR',
  '拉脱维亚': 'EUR',
  '立陶宛': 'EUR',
  '波斯尼亚和黑塞哥维那': 'BAM',
  '科索沃': 'EUR',
  '法罗群岛': 'DKK',
  '格陵兰': 'DKK',
  '奥兰群岛': 'EUR',
  '马耳他': 'EUR',
  '安道尔': 'EUR',
  '摩纳哥': 'EUR',
  '圣马力诺': 'EUR',
  '梵蒂冈': 'EUR',
  '根西岛': 'GBP',
  '泽西岛': 'GBP',
  '马恩岛': 'GBP',
  '直布罗陀': 'GIP',
  '福克兰群岛': 'FKP',
  '圣赫勒拿': 'SHP',
  '蒙特塞拉特': 'XCD',
  '安圭拉': 'XCD',
  '英属维尔京群岛': 'USD',
  '开曼群岛': 'KYD',
  '特克斯和凯科斯群岛': 'USD',
  '百慕大': 'BMD',
  '巴哈马': 'BSD',
  '伯利兹': 'BZD',
  '危地马拉': 'GTQ',
  '洪都拉斯': 'HNL',
  '萨尔瓦多': 'USD',
  '尼加拉瓜': 'NIO',
  '哥斯达黎加': 'CRC',
  '巴拿马': 'USD',
  '古巴': 'CUP',
  '多米尼加': 'DOP',
  '海地': 'HTG',
  '牙买加': 'JMD',
  '巴巴多斯': 'BBD',
  '特立尼达和多巴哥': 'TTD',
  '格林纳达': 'XCD',
  '圣卢西亚': 'XCD',
  '圣基茨和尼维斯': 'XCD',
  '圣文森特和格林纳丁斯': 'XCD',
  '多米尼克': 'XCD',
  '安提瓜和巴布达': 'XCD',
  '阿鲁巴': 'AWG',
  '库拉索': 'XCG',
  '圣马丁': 'XCG',
  '圣巴托洛缪': 'EUR',
  '法属圣马丁': 'EUR',
  '英属维尔京群岛': 'USD',
  '美属维尔京群岛': 'USD',
  '波多黎各': 'USD',
  '哥伦比亚': 'COP',
  '委内瑞拉': 'VES',
  '圭亚那': 'GYD',
  '苏里南': 'SRD',
  '厄瓜多尔': 'USD',
  '秘鲁': 'PEN',
  '玻利维亚': 'BOB',
  '智利': 'CLP',
  '阿根廷': 'ARS',
  '乌拉圭': 'UYU',
  '巴拉圭': 'PYG',
  '巴西': 'BRL',
  '法属圭亚那': 'EUR',
  '马提尼克': 'EUR',
  '瓜德罗普': 'EUR',
  '圣皮埃尔和密克隆': 'EUR',
  '新喀里多尼亚': 'XPF',
  '法属波利尼西亚': 'XPF',
  '瓦利斯和富图纳': 'XPF',
  '留尼汪': 'EUR',
  '马约特': 'EUR',
  '法属南部和南极领地': 'EUR',
  '摩洛哥': 'MAD',
  '阿尔及利亚': 'DZD',
  '突尼斯': 'TND',
  '利比亚': 'LYD',
  '埃及': 'EGP',
  '毛里塔尼亚': 'MRO',
  '马里': 'XOF',
  '布基纳法索': 'XOF',
  '塞内加尔': 'XOF',
  '几内亚': 'GNF',
  '几内亚比绍': 'GWP',
  '佛得角': 'CVE',
  '冈比亚': 'GMD',
  '塞拉利昂': 'SLL',
  '利比里亚': 'LRD',
  '科特迪瓦': 'XOF',
  '加纳': 'GHS',
  '多哥': 'XOF',
  '贝宁': 'XOF',
  '尼日尔': 'XOF',
  '尼日利亚': 'NGN',
  '喀麦隆': 'XAF',
  '中非': 'XAF',
  '乍得': 'XAF',
  '赤道几内亚': 'XAF',
  '加蓬': 'XAF',
  '刚果（布）': 'XAF',
  '刚果（金）': 'CDF',
  '安哥拉': 'AOA',
  '赞比亚': 'ZMW',
  '马拉维': 'MWK',
  '莫桑比克': 'MZN',
  '坦桑尼亚': 'TZS',
  '布隆迪': 'BIF',
  '卢旺达': 'RWF',
  '乌干达': 'UGX',
  '肯尼亚': 'KES',
  '南苏丹': 'SSP',
  '苏丹': 'SDG',
  '埃塞俄比亚': 'ETB',
  '厄立特里亚': 'ERN',
  '吉布提': 'DJF',
  '索马里': 'SOS',
  '利比亚': 'LYD',
  '博茨瓦纳': 'BWP',
  '莱索托': 'LSL',
  '斯威士兰': 'SZL',
  '纳米比亚': 'NAD',
  '南非': 'ZAR',
  '津巴布韦': 'ZWG',
  '科摩罗': 'KMF',
  '马达加斯加': 'MGA',
  '毛里求斯': 'MUR',
  '塞舌尔': 'SCR',
  '马尔代夫': 'MVR',
  '斯里兰卡': 'LKR',
  '印度': 'INR',
  '尼泊尔': 'NPR',
  '不丹': 'BTN',
  '孟加拉国': 'BDT',
  '巴基斯坦': 'PKR',
  '阿富汗': 'AFN',
  '伊朗': 'IRR',
  '伊拉克': 'IQD',
  '约旦': 'JOD',
  '科威特': 'KWD',
  '黎巴嫩': 'LBP',
  '阿曼': 'OMR',
  '卡塔尔': 'QAR',
  '沙特阿拉伯': 'SAR',
  '叙利亚': 'SYP',
  '阿联酋': 'AED',
  '也门': 'YER',
  '巴林': 'BHD',
  '以色列': 'ILS',
  '巴勒斯坦': 'ILS',
  '土耳其': 'TRY',
  '塞浦路斯': 'EUR',
  '北塞浦路斯土耳其共和国': 'TRY',
  '格鲁吉亚': 'GEL',
  '亚美尼亚': 'AMD',
  '阿塞拜疆': 'AZN',
  '俄罗斯': 'RUB',
  '乌克兰': 'UAH',
  '白俄罗斯': 'BYN',
  '摩尔多瓦': 'MDL',
  '波兰': 'PLN',
  '斯洛伐克': 'EUR',
  '斯洛文尼亚': 'EUR',
  '匈牙利': 'HUF',
  '捷克': 'CZK',
  '奥地利': 'EUR',
  '比利时': 'EUR',
  '荷兰': 'EUR',
  '卢森堡': 'EUR',
  '德国': 'EUR',
  '法国': 'EUR',
  '意大利': 'EUR',
  '西班牙': 'EUR',
  '葡萄牙': 'EUR',
  '爱尔兰': 'EUR',
  '芬兰': 'EUR',
  '希腊': 'EUR',
  '瑞典': 'SEK',
  '挪威': 'NOK',
  '丹麦': 'DKK',
  '冰岛': 'ISK',
  '英国': 'GBP',
  '瑞士': 'CHF',
  '列支敦士登': 'CHF',
  '塞尔维亚': 'RSD',
  '克罗地亚': 'HRK',
  '黑山': 'EUR',
  '马其顿': 'MKD',
  '阿尔巴尼亚': 'ALL',
  '保加利亚': 'BGN',
  '罗马尼亚': 'RON',
  '爱沙尼亚': 'EUR',
  '拉脱维亚': 'EUR',
  '立陶宛': 'EUR',
  '波斯尼亚和黑塞哥维那': 'BAM',
  '科索沃': 'EUR',
  '法罗群岛': 'DKK',
  '格陵兰': 'DKK',
  '奥兰群岛': 'EUR',
  '马耳他': 'EUR',
  '安道尔': 'EUR',
  '摩纳哥': 'EUR',
  '圣马力诺': 'EUR',
  '梵蒂冈': 'EUR',
  '根西岛': 'GBP',
  '泽西岛': 'GBP',
  '马恩岛': 'GBP',
  '直布罗陀': 'GIP',
  '福克兰群岛': 'FKP',
  '圣赫勒拿': 'SHP',
  '蒙特塞拉特': 'XCD',
  '安圭拉': 'XCD',
  '英属维尔京群岛': 'USD',
  '开曼群岛': 'KYD',
  '特克斯和凯科斯群岛': 'USD',
  '百慕大': 'BMD',
  '巴哈马': 'BSD',
  '伯利兹': 'BZD',
  '危地马拉': 'GTQ',
  '洪都拉斯': 'HNL',
  '萨尔瓦多': 'USD',
  '尼加拉瓜': 'NIO',
  '哥斯达黎加': 'CRC',
  '巴拿马': 'USD',
  '古巴': 'CUP',
  '多米尼加': 'DOP',
  '海地': 'HTG',
  '牙买加': 'JMD',
  '巴巴多斯': 'BBD',
  '特立尼达和多巴哥': 'TTD',
  '格林纳达': 'XCD',
  '圣卢西亚': 'XCD',
  '圣基茨和尼维斯': 'XCD',
  '圣文森特和格林纳丁斯': 'XCD',
  '多米尼克': 'XCD',
  '安提瓜和巴布达': 'XCD',
  '阿鲁巴': 'AWG',
  '库拉索': 'XCG',
  '圣马丁': 'XCG',
  '圣巴托洛缪': 'EUR',
  '法属圣马丁': 'EUR',
  '英属维尔京群岛': 'USD',
  '美属维尔京群岛': 'USD',
  '波多黎各': 'USD',
  '哥伦比亚': 'COP',
  '委内瑞拉': 'VES',
  '圭亚那': 'GYD',
  '苏里南': 'SRD',
  '厄瓜多尔': 'USD',
  '秘鲁': 'PEN',
  '玻利维亚': 'BOB',
  '智利': 'CLP',
  '阿根廷': 'ARS',
  '乌拉圭': 'UYU',
  '巴拉圭': 'PYG',
  '巴西': 'BRL',
  '法属圭亚那': 'EUR',
  '马提尼克': 'EUR',
  '瓜德罗普': 'EUR',
  '圣皮埃尔和密克隆': 'EUR',
  '新喀里多尼亚': 'XPF',
  '法属波利尼西亚': 'XPF',
  '瓦利斯和富图纳': 'XPF',
  '留尼汪': 'EUR',
  '马约特': 'EUR',
  '法属南部和南极领地': 'EUR',
  '摩洛哥': 'MAD',
  '阿尔及利亚': 'DZD',
  '突尼斯': 'TND',
  '利比亚': 'LYD',
  '埃及': 'EGP',
  '毛里塔尼亚': 'MRO',
  '马里': 'XOF',
  '布基纳法索': 'XOF',
  '塞内加尔': 'XOF',
  '几内亚': 'GNF',
  '几内亚比绍': 'GWP',
  '佛得角': 'CVE',
  '冈比亚': 'GMD',
  '塞拉利昂': 'SLL',
  '利比里亚': 'LRD',
  '科特迪瓦': 'XOF',
  '加纳': 'GHS',
  '多哥': 'XOF',
  '贝宁': 'XOF',
  '尼日尔': 'XOF',
  '尼日利亚': 'NGN',
  '喀麦隆': 'XAF',
  '中非': 'XAF',
  '乍得': 'XAF',
  '赤道几内亚': 'XAF',
  '加蓬': 'XAF',
  '刚果（布）': 'XAF',
  '刚果（金）': 'CDF',
  '安哥拉': 'AOA',
  '赞比亚': 'ZMW',
  '马拉维': 'MWK',
  '莫桑比克': 'MZN',
  '坦桑尼亚': 'TZS',
  '布隆迪': 'BIF',
  '卢旺达': 'RWF',
  '乌干达': 'UGX',
  '肯尼亚': 'KES',
  '南苏丹': 'SSP',
  '苏丹': 'SDG',
  '埃塞俄比亚': 'ETB',
  '厄立特里亚': 'ERN',
  '吉布提': 'DJF',
  '索马里': 'SOS',
  '利比亚': 'LYD',
  '博茨瓦纳': 'BWP',
  '莱索托': 'LSL',
  '斯威士兰': 'SZL',
  '纳米比亚': 'NAD',
  '南非': 'ZAR',
  '津巴布韦': 'ZWG',
  '科摩罗': 'KMF',
  '马达加斯加': 'MGA',
  '毛里求斯': 'MUR',
  '塞舌尔': 'SCR',
  '马尔代夫': 'MVR',
  '斯里兰卡': 'LKR',
  '印度': 'INR',
  '尼泊尔': 'NPR',
  '不丹': 'BTN',
  '孟加拉国': 'BDT',
  '巴基斯坦': 'PKR',
  '阿富汗': 'AFN',
  '伊朗': 'IRR',
  '伊拉克': 'IQD',
  '约旦': 'JOD',
  '科威特': 'KWD',
  '黎巴嫩': 'LBP',
  '阿曼': 'OMR',
  '卡塔尔': 'QAR',
  '沙特阿拉伯': 'SAR',
  '叙利亚': 'SYP',
  '阿联酋': 'AED',
  '也门': 'YER',
  '巴林': 'BHD',
  '以色列': 'ILS',
  '巴勒斯坦': 'ILS',
  '土耳其': 'TRY'
}

/**
 * 构建"任意输入 → code"的查找索引
 * @param {Array} currencies_list - store.currencies_list
 * @returns {Object} key 为可搜索字符串，value 为大写 code
 */
export function buildCodeIndex(currencies_list) {
  const idx = {}
  for (const item of currencies_list) {
    const code = item.currencies?.code
    if (!code) continue
    idx[code] = code
    idx[code.toLowerCase()] = code
    const zh = item.translations?.zho
    if (zh) {
      if (zh.official) idx[zh.official] = code
      if (zh.common) idx[zh.common] = code
    }
    if (item.currencies?.name) idx[item.currencies.name] = code
    if (item.name) idx[item.name] = code
    if (item.officialName) idx[item.officialName] = code
  }
  for (const [alias, c] of Object.entries(CN_ALIASES)) {
    if (!idx[alias]) idx[alias] = c
  }
  return idx
}

/**
 * 判断单条币种是否匹配搜索关键词（任意维度：code/中文名/英文名/简称）
 * @param {Object} item - currencies_list 中的单项
 * @param {string} kwLower - 已 trim + toLowerCase 的关键词
 * @returns {boolean}
 */
export function matchCurrencyByKeyword(item, kwLower) {
  if (!kwLower) return true
  // 1. 三字码包含匹配
  const code = String(item.currencies?.code || '').toLowerCase()
  if (code.includes(kwLower)) return true
  // 2. 中文名包含匹配（translations.zho.official / common）
  const zh = item.translations?.zho
  if (zh) {
    if (zh.official && String(zh.official).toLowerCase().includes(kwLower)) return true
    if (zh.common && String(zh.common).toLowerCase().includes(kwLower)) return true
  }
  // 3. 币种英文名包含匹配
  const curName = String(item.currencies?.name || '').toLowerCase()
  if (curName.includes(kwLower)) return true
  // 4. 国家英文名包含匹配
  const name = String(item.name || '').toLowerCase()
  if (name.includes(kwLower)) return true
  // 5. CN_ALIASES 兜底：是否有别名匹配 kw 且其 code 等于本币种 code
  const upperCode = item.currencies?.code?.toUpperCase()
  if (upperCode) {
    for (const [alias, c] of Object.entries(CN_ALIASES)) {
      if (c === upperCode && alias.toLowerCase().includes(kwLower)) return true
    }
  }
  return false
}
